// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface SimpleStorage$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "SimpleStorage";
  readonly sourceName: "contracts/SimpleStorage.sol";
  readonly abi: [{"inputs":[],"name":"get","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"uint256","name":"newValue","type":"uint256"}],"name":"set","outputs":[],"stateMutability":"nonpayable","type":"function"}];
  readonly bytecode: "0x6080604052348015600e575f80fd5b5060a58061001b5f395ff3fe6080604052348015600e575f80fd5b50600436106030575f3560e01c806360fe47b11460345780636d4ce63c146045575b5f80fd5b6043603f3660046059565b5f55565b005b5f5460405190815260200160405180910390f35b5f602082840312156068575f80fd5b503591905056fea26469706673582212202a85bc425a9ac1899ba32df450ec9aad26263c4fc8a0f1f61668484a05bccad164736f6c63430008180033";
  readonly deployedBytecode: "0x6080604052348015600e575f80fd5b50600436106030575f3560e01c806360fe47b11460345780636d4ce63c146045575b5f80fd5b6043603f3660046059565b5f55565b005b5f5460405190815260200160405180910390f35b5f602082840312156068575f80fd5b503591905056fea26469706673582212202a85bc425a9ac1899ba32df450ec9aad26263c4fc8a0f1f61668484a05bccad164736f6c63430008180033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/SimpleStorage.sol";
  readonly buildInfoId: "solc-0_8_24-1d4e8ae7aa6980d777caf64232690d88f5ac02a4";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["SimpleStorage"]: SimpleStorage$Type;
    ["contracts/SimpleStorage.sol:SimpleStorage"]: SimpleStorage$Type;
  }
}